### PR TITLE
BugFix: fix radar chart tick point not scaling

### LINKED ISSUE #1078: RadarChart tick and graph point scale do not match
**Describe the bug**
RadarChart tick and graph point scale do not match

If a point has a value of 15 and a tick line has a value of 15, I would expect the point to fall on the line. This is not always the case

The values in tick titles do not always match with the values of the points on the graph because
- points are drawn assuming the graph center = 0
- tick title values assume that the graph center = (minValue - ((maxValue - minValue) / tickCount))

**To Reproduce**
```
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: UsageRadarChart(),
        ),
      ),
    );
  }
}

class UsageRadarChart extends StatelessWidget {
  const UsageRadarChart({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      height: 300,
      child:
        RadarChart(
          RadarChartData(
            tickCount: 2,
            dataSets: [
              RadarDataSet(
                dataEntries: [
                  const RadarEntry(value: 15),
                  const RadarEntry(value: 20),
                  const RadarEntry(value: 20),
                ]
              )
            ],
          ),
        ),
    );
  }
}
```

**Screenshots**
Expected | Actual
:-------------------------:|:-------------------------:
Points: [15, 20, 20] | Points: [15, 20, 20]
Screen Shot 2022-07-01 at 7 22 54 PM | Screen Shot 2022-07-01 at 7 22 30 PM

**Versions**
 - which version of the Flutter are you using?
```
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (8 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```
 - which version of the FlChart are you using?
   - 0.55.0 but I've been able to reproduce it as far back as 0.45.0 (I didn't try any further back)

### PR DESCRIPTION
**Pull request by nav-28**
Resolves #1078

This pr solves the problem described in the above issue. The code is taken from a closed pr #1084 as the pr was not merged due to conflicts.

### CODE REVIEW

File: lib/src/chart/radar_chart/radar_chart_painter.dart [hunk 1]
```diff
@@ -68,6 +68,60 @@ class RadarChartPainter extends BaseChartPainter<RadarChartData> {
...
+
+  @visibleForTesting
+  double getScaledPoint(RadarEntry point, double radius, RadarChartData data) {
+    final centerValue = getChartCenterValue(data);
+    final distanceFromPointToCenter = point.value - centerValue;
+    var distanceFromMaxToCenter = data.maxEntry.value - centerValue;
+
+    if (distanceFromMaxToCenter == 0) {
+      const preventDividingByZero = 0.001;
+      distanceFromMaxToCenter += preventDividingByZero;
```
Comment (imaNNeo) [inline lib/src/chart/radar_chart/radar_chart_painter.dart:95]: What if you return a value directly here? (instead of doing this trick)
I think you can return something like `0`

**Comment by imaNNeo** [comment]
You need to update the [CHANGELOG.md](https://github.com/imaNNeo/fl_chart/blob/master/CHANGELOG.md) file to add this change
Please check out our [CONTRIBUTING](https://github.com/imaNNeo/fl_chart/blob/master/CONTRIBUTING.md) guideline.

**Comment by imaNNeo** [comment]
Ready to merge

**Comment by imaNNeo** [comment]
I cannot merge this branch.
You needed to rebase your branch. We don't accept merge commits in your branch.
Please reset your commits.

**Comment by nav-28** [comment]
my bad, fixed it

**Comment by imaNNeo** [comment]
We have a conflict again (I merged a PR right now). 
Sorry about that.

**Comment by imaNNeo** [comment]
Yaay 🎉
Thanks for your contribution!
